group: travis_latest
language: python
cache: pip
python:
- 3.7
install:
- pip install -r monkey/monkey_island/requirements.txt
- pip install flake8 pytest dlint pylint
- pip install -r monkey/infection_monkey/requirements_linux.txt
before_script:
- flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
- flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
- monkey/monkey_island/cc/set_server_config.py testing
script:
- cd monkey  # This is our source dir
- python -m pytest  # Have to use `python -m pytest` instead of `pytest` to add "{$builddir}/monkey/monkey" to sys.path.
notifications:
  slack:
      rooms:
      - infectionmonkey:QaXbsx4g7tHFJW0lhtiBmoAg#ci
      - infectionmonkey:QaXbsx4g7tHFJW0lhtiBmoAg#github
      on_success: always
      on_failure: always
  email:
      on_success: change
      on_failure: always
