version: '3.3'

services:
  db:
    image: mongo:4
    restart: always
    volumes:
      - db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
  monkey:
    depends_on:
      - db
    build: .
    image: monkey:latest
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb://root:test@db:27017/

volumes:
  db_data:
